#!/usr/bin/env python3

import os
import subprocess
import sys

def main():
    dir = sys.argv[1]
    ok = 0
    cnt = 0

    for filename in os.listdir(dir + "/input"):
        test_name = filename[:-4]
        input_file = dir + "/input/" + test_name + ".txt"
        output_file = "output"
        subprocess.run(["./a.exe", input_file, "11", output_file], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        expected_output = open(dir + "/output/" + test_name + ".txt", "r").readlines()[0].strip().split(" ")
        actual_output = open(output_file, "r").readlines()[0].strip().split(" ")
        cnt += 1
        if expected_output[:len(actual_output)] == actual_output:
            ok += 1
        else:
            print(test_name + " FAIL")
        
    print(f"Passesd {ok}/{cnt}")
        
if __name__ == "__main__":
    main()
